# Project information
site_name: HyPhy - Hypothesis Testing using Phylogenies
site_description: null
site_author: VEG
site_url: http://squidfunk.github.io/mkdocs-material/

# Copyright
copyright: null

# Documentation and theme
theme_dir: material

# extra_templates

# Options
extra:
  version: 0.2.4
  logo: images/logo.svg
  github:
    download_release: true
  author:
    github: veg
    twitter: hyphy_software

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
  - mdx_math:
      enable_dollar_delimiter: True

    

extra_javascript: 
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - assets/mathjaxhelper.js

# Google Analytics
google_analytics: ['UA-36723568-3', 'mkdocs.org']

# Page tree
pages:
  - Home: 'index.html'
  - Installation: 'installation.md'
  - Getting Started : 'getting-started.md'
  - Glossary: 'glossary.md'
  - Resources : 'resources.md'
  - Methods:
    - General Information : 'methods/general.md'
    - Selection : 'methods/selection-methods.md'
    - Other : 'methods/other-methods.md'
  - Tutorials: 
    - Using HyPhy to Detect Selection : 'tutorials/current-release-tutorial.md'
    - v2.3 Quick Start : 'tutorials/dev-branch-tutorial.md'
    
